### ISSUE TITLE
Add dark mode

### ISSUE THREAD

**Issue by MichaelCurrin** [MichaelCurrin/badge-generator#106]
From inspecting in Chrome / Nativefier:

<img width="761" alt="Screen Shot 2021-05-12 at 9 26 41 am" src="https://user-images.githubusercontent.com/18750745/117935675-4099e280-b304-11eb-9e70-a2c29e67886e.png">

<img width="750" alt="Screen Shot 2021-05-12 at 9 26 44 am" src="https://user-images.githubusercontent.com/18750745/117935694-468fc380-b304-11eb-8171-9ecbba23f752.png">

**Comment by minhhang107** [comment]
I'd like to work on this one. Can you assign me?

**Comment by MichaelCurrin** [comment]
Sure!

I've not implemented a dark mode before and the screenshots of a mock are not accessible (poor contrast). So you can suggest a solution. 

Maybe white text on a grey background will work and special attention for links, navbar, and codeblocks. I'd also be happy to keep the codeblocks light as in screenshot, as the work to change the highlight.js theme will be more complicated 

And a toggle for dark mode. There was recent work to have a global store in store.ts if you want to persist `darkMode=false` there.

**Comment by MichaelCurrin** [comment]
For inspiration 

- read and set theme https://dev.to/tqbit/create-your-own-dark-mode-toggle-component-with-vue-js-1284
- DarkMode component  through vue-a11y https://github.com/vue-a11y/vue-dark-mode/tree/master/docs/guide

**Comment by minhhang107** [comment]
I'll probably use white text for dark mode. And you're right about the codeblock. I've been looking at it and can't find a solution to switch highlight.js theme yet so keeping the light background should be good for now.
